import express from "express";
import pinoHttp from "pino-http";
import { logger } from "./lib/logger.ts";
import { attachAuth } from "./middleware/auth.ts";
import { killSwitch } from "./middleware/kill-switch.ts";
import { ipRateLimiter } from "./middleware/rate-limit.ts";
import { agentChatRouter } from "./routes/agent-chat.ts";
import { agentInstructionRouter } from "./routes/agent-instruction.ts";
import { agentLiquidityRouter } from "./routes/agent-liquidity.ts";
import { agentPortfolioRouter } from "./routes/agent-portfolio.ts";
import { agentUnifiedBalanceRouter } from "./routes/agent-unified-balance.ts";
import { cronRebalanceRouter } from "./routes/cron-rebalance.ts";
import { cronPegSyncRouter } from "./routes/cron-peg-sync.ts";
import { cronSportsSyncRouter } from "./routes/cron-sports-sync.ts";
import { adminSpPoolRouter } from "./routes/admin-sp-pool.ts";
import { sportsSlateRouter } from "./routes/sports-slate.ts";
import { strategiesRouter } from "./routes/strategies.ts";
import { marketTradeRouter } from "./routes/market-trade.ts";
import { marketPositionsRouter } from "./routes/market-positions.ts";
import { marketFillsRouter } from "./routes/market-fills.ts";
import { marketDetailRouter } from "./routes/market-detail.ts";
import { cronStrategiesRouter } from "./routes/cron-strategies.ts";
import { cronResolutionRouter } from "./routes/cron-resolution.ts";
import { cronIntentsRouter } from "./routes/cron-intents.ts";
import { x402ServiceRouter } from "./routes/x402-service.ts";
import { agentQueryRouter } from "./routes/agent-query.ts";
import { agentSendRouter } from "./routes/agent-send.ts";
import { agentSwapRouter } from "./routes/agent-swap.ts";
import { agentWalletsRouter } from "./routes/agent-wallets.ts";
import { commandParseRouter } from "./routes/command-parse.ts";
import { analyticsRouter } from "./routes/analytics.ts";
import { analyzeRouter } from "./routes/analyze.ts";
import { analyzeChatRouter } from "./routes/analyze-chat.ts";
import { healthRouter } from "./routes/health.ts";
import { liquidityAddRouter } from "./routes/liquidity-add.ts";
import { liquidityRemoveRouter } from "./routes/liquidity-remove.ts";
import { poolCreateRouter } from "./routes/pool-create.ts";
import { poolStateRouter } from "./routes/pool-state.ts";
import { poolsRouter } from "./routes/pools.ts";
import { rpcProxyRouter } from "./routes/rpc-proxy.ts";
import { earningsRouter } from "./routes/earnings.ts";
import { portfolioRouter } from "./routes/portfolio.ts";
import { positionsRouter } from "./routes/positions.ts";
import { quoteRouter } from "./routes/quote.ts";
import { swapRouter } from "./routes/swap.ts";
import { tokenPricesRouter } from "./routes/token-prices.ts";
import { pairPriceChartRouter } from "./routes/pair-price-chart.ts";
import { v4SwapRouter } from "./routes/v4-swap.ts";

/**
 * Express app factory, shared by the standalone server (`index.ts`,
 * local dev) and the Vercel serverless entrypoint (`api/index.ts`).
 * Keeping route/middleware registration here means both run identical
 * wiring — the only difference is `index.ts` calls `.listen()`.
 */
export const app = express();
app.set("trust proxy", 1);
app.use(pinoHttp({ logger }));
app.use(express.json());
app.use(ipRateLimiter);
app.use(killSwitch);
app.use(attachAuth);

app.use(healthRouter);
app.use(rpcProxyRouter);
app.use(poolsRouter);
app.use(poolCreateRouter);
app.use(poolStateRouter);
app.use(liquidityAddRouter);
app.use(liquidityRemoveRouter);
app.use(positionsRouter);
app.use(earningsRouter);
app.use(portfolioRouter);
app.use(quoteRouter);
app.use(swapRouter);
app.use(tokenPricesRouter);
app.use(pairPriceChartRouter);
app.use(v4SwapRouter);
app.use(agentWalletsRouter);
app.use(agentSendRouter);
app.use(agentSwapRouter);
app.use(agentLiquidityRouter);
app.use(agentQueryRouter);
app.use(agentPortfolioRouter);
app.use(agentUnifiedBalanceRouter);
app.use(cronRebalanceRouter);
app.use(cronPegSyncRouter);
app.use(cronSportsSyncRouter);
app.use(adminSpPoolRouter);
app.use(sportsSlateRouter);
app.use(strategiesRouter);
app.use(marketTradeRouter);
app.use(marketPositionsRouter);
app.use(marketFillsRouter);
app.use(marketDetailRouter);
app.use(cronStrategiesRouter);
app.use(cronResolutionRouter);
app.use(cronIntentsRouter);
app.use(x402ServiceRouter);
app.use(agentChatRouter);
app.use(agentInstructionRouter);
app.use(commandParseRouter);
app.use(analyticsRouter);
app.use(analyzeRouter);
app.use(analyzeChatRouter);
